### ISSUE TITLE
Add link checker to make sure all links are up

### ISSUE THREAD

**Issue by simeg** [learn-anything/command-line-tools#10]
I recently wrote this tool called [`urlsup`](https://github.com/simeg/urlsup) that parses and checks all links within a repository. I think it would be useful for this repo as it contains lots of links, and of course you want them to be available.

**Comment by nikitavoloboev** [comment]
very cool, thanks

I added it myself but I am curious why you didn't make this a PR so I could merge it instantly :)

**Comment by simeg** [comment]
Thanks for adding it to the list, but I meant to add it to be used for this repository 😄

I just ran it on my machine with 30 threads and it took 7 seconds, and I found 8 problems.

```
> Issues
   1. 404 https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man8/softwareupdate.8.html
   2. 404 https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man8/PlistBuddy.8.html
   3. 404 https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man8/asr.8.html
   4. 404 https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/time.1.html
   5. 404 https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/defaults.1.html
   6. 404 https://github.com/jorgegonzalez/snapterm
   7. https://www.explainbshell.com/explain/bash error trying to connect: dns error: failed to lookup address information: Name or service not known
   8. 404 https://nixos.org/releases/nix/nix-1.7/manual/
```

I noticed you don't have any CI setup but if you would consider using Travis CI it's easy to setup. Any other CI service supporting docker would also be easy to setup. [See instructions here](https://github.com/simeg/urlsup#travis-ci).
